version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: winston
    versions:
    - ">= 3.a, < 4"
  - dependency-name: husky
    versions:
    - 5.1.0
