language: node_js
node_js:
- '0.12'
- '4'
- '5'
sudo: false
install:
- npm install
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install jq      ; fi
- PACKAGE_VERSION=`jq -r .version package.json`
- PACKAGE_NAME=`jq -r .name package.json`
- echo "Checking for existance of already-published $PACKAGE_NAME@$PACKAGE_VERSION"
- if [ -n "$(npm info $PACKAGE_NAME@$PACKAGE_VERSION)" ]; then echo "Build version exists on NPM"; exit 1; fi
- npm test

